name: Docker CI

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Add git note
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git fetch origin "refs/notes/*:refs/notes/*"
          git notes add -m "published" ${{ github.sha }}
          git push origin refs/notes/commits
